# Zitadel, fully managed: project, both applications, login behavior
# (self-registration), and branding (theme + watermark removal).
#
# The payoff of managing this here rather than in the console: the client
# IDs, the web client secret, and the project ID flow *directly* from
# these resources into the container env in containers.tf — nothing is
# copy-pasted through GitHub variables, and recreating the instance from
# scratch is one apply.
#
# Bootstrap (the one thing Terraform can't create is its own credential):
# a machine user with Org Owner + a PAT — see infra/README.md.

provider "zitadel" {
  domain       = trimprefix(var.zitadel_domain, "https://")
  access_token = var.zitadel_pat
}

# ------------------------------------------------------------------
# Project + applications
# ------------------------------------------------------------------

resource "zitadel_project" "order_api" {
  name   = "order-api"
  org_id = var.zitadel_org_id

  # No role-based authorization in this system (ownership is per-user in
  # the orders table), so keep all role machinery off.
  project_role_assertion   = false
  project_role_check       = false
  has_project_check        = false
  private_labeling_setting = "PRIVATE_LABELING_SETTING_UNSPECIFIED"
}

# The Go backend. Only its client ID matters (local JWT validation checks
# the token audience against it); no credentials are ever generated or
# used because the API never authenticates *to* Zitadel.
resource "zitadel_application_api" "backend" {
  org_id           = var.zitadel_org_id
  project_id       = zitadel_project.order_api.id
  name             = "order-api-backend"
  auth_method_type = "API_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT"
}

# The Next.js BFF: confidential Web app, code flow + PKCE, client secret
# generated by Zitadel and wired straight into the web container.
resource "zitadel_application_oidc" "web" {
  org_id     = var.zitadel_org_id
  project_id = zitadel_project.order_api.id
  name       = "order-web"

  redirect_uris = [
    "https://${var.web_hostname}/api/auth/callback/zitadel",
    "http://localhost:3000/api/auth/callback/zitadel", # local dev
  ]
  post_logout_redirect_uris = [
    "https://${var.web_hostname}/",
    "http://localhost:3000/",
  ]

  response_types   = ["OIDC_RESPONSE_TYPE_CODE"]
  grant_types      = ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"]
  app_type         = "OIDC_APP_TYPE_WEB"
  auth_method_type = "OIDC_AUTH_METHOD_TYPE_BASIC"
  version          = "OIDC_VERSION_1_0"

  # Dev Mode permits the plain-http localhost redirect above. Production
  # URIs are https, so the practical risk is nil for this app; drop the
  # localhost entries and set this to false if that changes.
  dev_mode = true

  # THE critical switch: JWT access tokens instead of Zitadel's default
  # opaque ones. Without it the Go API's local validation rejects every
  # request with 401.
  access_token_type = "OIDC_TOKEN_TYPE_JWT"

  access_token_role_assertion = false
  id_token_role_assertion     = false
  id_token_userinfo_assertion = false
  clock_skew                  = "0s"
}

# ------------------------------------------------------------------
# Login behavior: hosted registration enabled (goal 2 — no custom forms)
# ------------------------------------------------------------------

resource "zitadel_login_policy" "default_org" {
  org_id = var.zitadel_org_id

  user_login         = true
  allow_register     = true  # self-registration on the hosted pages
  allow_external_idp = false # no social logins configured (yet)

  force_mfa            = false
  force_mfa_local_only = false
  passwordless_type    = "PASSWORDLESS_TYPE_ALLOWED"
  second_factors       = ["SECOND_FACTOR_TYPE_OTP", "SECOND_FACTOR_TYPE_U2F"]
  multi_factors        = ["MULTI_FACTOR_TYPE_U2F_WITH_VERIFICATION"]

  hide_password_reset      = false
  ignore_unknown_usernames = false
  allow_domain_discovery   = false
  disable_login_with_email = false
  disable_login_with_phone = true # no SMS provider configured
  default_redirect_uri     = "https://${var.web_hostname}"

  # Standard Zitadel lifetimes; the session length users experience is
  # governed by the app's 12h Auth.js session, not these.
  password_check_lifetime       = "240h0m0s"
  external_login_check_lifetime = "240h0m0s"
  multi_factor_check_lifetime   = "24h0m0s"
  second_factor_check_lifetime  = "24h0m0s"
  mfa_init_skip_lifetime        = "720h0m0s"
}

# ------------------------------------------------------------------
# Branding: palette from web/src/app/globals.css, watermark off
# ------------------------------------------------------------------

resource "zitadel_label_policy" "default_org" {
  org_id = var.zitadel_org_id

  # Light theme — mirrors the app: paper / ink / teal / danger.
  primary_color    = "#0b6e7f"
  background_color = "#f4f2ec"
  font_color       = "#182430"
  warn_color       = "#b3261e"

  # Dark theme — sensible inversion, same teal identity.
  primary_color_dark    = "#0b6e7f"
  background_color_dark = "#182430"
  font_color_dark       = "#f4f2ec"
  warn_color_dark       = "#b3261e"

  hide_login_name_suffix = true # show "alice", not "alice@org.domain"
  disable_watermark      = true # removes "Powered by ZITADEL"

  # Zitadel stages branding as a preview until activated; this applies it.
  set_active = true

  # Logo/icon/font uploads are supported here too (logo_path + logo_hash),
  # but binary assets in a git repo age badly — upload once via console
  # (Branding → drag & drop) if wanted; Terraform won't fight it.
}
