package handlers

import (
	"crypto/rand"
	"encoding/base32"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"order-api/auth"
	"order-api/db"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// Server holds database operations via dependency injection.
// db.Querier is generated by sqlc (emit_interface: true), so it stays in
// sync with queries.sql automatically. *db.Queries satisfies it; tests
// substitute a stub.
type Server struct {
	Queries db.Querier
}

// anonymousOwner is the owner recorded when auth is disabled (local dev
// without ZITADEL_DOMAIN): every request maps to one shared owner, which
// reproduces the pre-auth "everyone sees everything" behavior — but only
// in the explicitly unauthenticated configuration.
const anonymousOwner = "anonymous"

// ownerID resolves the order owner for a request: the Zitadel subject
// when auth is enabled, anonymousOwner otherwise. All queries are scoped
// by this value, so users can only ever see and mutate their own orders.
func ownerID(r *http.Request) string {
	if id := auth.UserID(r.Context()); id != "" {
		return id
	}
	return anonymousOwner
}

// newOrderID returns a server-generated order ID ("ord_" + 16 base32
// chars, 80 bits of randomness). Clients no longer supply IDs on POST —
// a POC-era awkwardness the handoff flagged for removal.
func newOrderID() (string, error) {
	var b [10]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("generating order id: %w", err)
	}
	return "ord_" + base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(b[:]), nil
}

func respondWithJSON(w http.ResponseWriter, status int, payload interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(payload); err != nil {
		slog.Error("respondWithJSON: encode failed", "error", err)
	}
}

// GET /orders
func (s *Server) GetOrders(w http.ResponseWriter, r *http.Request) {
	orders, err := s.Queries.GetOrders(r.Context(), ownerID(r))
	if err != nil {
		respondWithJSON(w, http.StatusInternalServerError, map[string]string{"error": "Failed to fetch orders"})
		return
	}
	if orders == nil {
		orders = []db.Order{} // encode [] instead of null for empty lists
	}
	respondWithJSON(w, http.StatusOK, orders)
}

// GET /orders/{id}
func (s *Server) GetOrderByID(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")

	order, err := s.Queries.GetOrder(r.Context(), db.GetOrderParams{ID: id, UserID: ownerID(r)})
	if err == pgx.ErrNoRows {
		// Also the answer for another user's order: scoping by user_id in
		// the query means "not yours" is indistinguishable from "not there".
		respondWithJSON(w, http.StatusNotFound, map[string]string{"error": "Order not found"})
		return
	} else if err != nil {
		respondWithJSON(w, http.StatusInternalServerError, map[string]string{"error": "Database error"})
		return
	}

	respondWithJSON(w, http.StatusOK, order)
}

// POST /orders
func (s *Server) CreateOrder(w http.ResponseWriter, r *http.Request) {
	var body struct {
		Item     string  `json:"item"`
		Quantity int32   `json:"quantity"`
		Price    float64 `json:"price"` // Accept as float64 from client JSON
	}

	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		respondWithJSON(w, http.StatusBadRequest, map[string]string{"error": "Invalid JSON payload"})
		return
	}

	if body.Item == "" {
		respondWithJSON(w, http.StatusBadRequest, map[string]string{"error": "Item is required"})
		return
	}

	// Safely convert float64 to pgtype.Numeric
	var priceNumeric pgtype.Numeric
	if err := priceNumeric.Scan(fmt.Sprintf("%.2f", body.Price)); err != nil {
		respondWithJSON(w, http.StatusBadRequest, map[string]string{"error": "Invalid price format"})
		return
	}

	id, err := newOrderID()
	if err != nil {
		respondWithJSON(w, http.StatusInternalServerError, map[string]string{"error": "Could not create order"})
		return
	}

	order, err := s.Queries.CreateOrder(r.Context(), db.CreateOrderParams{
		ID:       id,
		Item:     body.Item,
		Quantity: body.Quantity,
		Price:    priceNumeric,
		UserID:   ownerID(r),
	})
	if err != nil {
		respondWithJSON(w, http.StatusInternalServerError, map[string]string{"error": "Could not create order"})
		return
	}

	respondWithJSON(w, http.StatusCreated, order)
}

// PUT /orders/{id}
func (s *Server) UpdateOrder(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")

	var body struct {
		Item     string  `json:"item"`
		Quantity int32   `json:"quantity"`
		Price    float64 `json:"price"` // Accept as float64 from client JSON
	}

	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		respondWithJSON(w, http.StatusBadRequest, map[string]string{"error": "Invalid JSON payload"})
		return
	}

	// Safely convert float64 to pgtype.Numeric
	var priceNumeric pgtype.Numeric
	if err := priceNumeric.Scan(fmt.Sprintf("%.2f", body.Price)); err != nil {
		respondWithJSON(w, http.StatusBadRequest, map[string]string{"error": "Invalid price format"})
		return
	}

	order, err := s.Queries.UpdateOrder(r.Context(), db.UpdateOrderParams{
		ID:       id,
		Item:     body.Item,
		Quantity: body.Quantity,
		Price:    priceNumeric,
		UserID:   ownerID(r),
	})

	if err == pgx.ErrNoRows {
		respondWithJSON(w, http.StatusNotFound, map[string]string{"error": "Order not found"})
		return
	} else if err != nil {
		respondWithJSON(w, http.StatusInternalServerError, map[string]string{"error": "Could not update order"})
		return
	}

	respondWithJSON(w, http.StatusOK, order)
}

// DELETE /orders/{id}
func (s *Server) DeleteOrder(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")

	rows, err := s.Queries.DeleteOrder(r.Context(), db.DeleteOrderParams{ID: id, UserID: ownerID(r)})
	if err != nil {
		respondWithJSON(w, http.StatusInternalServerError, map[string]string{"error": "Could not delete order"})
		return
	}
	if rows == 0 {
		// :execrows finally makes the missing-ID case observable — the
		// old :exec version returned 200 no matter what.
		respondWithJSON(w, http.StatusNotFound, map[string]string{"error": "Order not found"})
		return
	}

	respondWithJSON(w, http.StatusOK, map[string]string{"message": "Order deleted"})
}

// Healthz is a public liveness endpoint (no auth) for Scaleway health
// checks and quick smoke tests. It deliberately does not ping the DB:
// serverless health checks are frequent and a per-check DB round trip
// would keep the Neon connection warm for no user benefit.
func Healthz(version string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		respondWithJSON(w, http.StatusOK, map[string]string{"status": "ok", "version": version})
	}
}
