// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID       string         `json:"id"`
	Item     string         `json:"item"`
	Quantity int32          `json:"quantity"`
	Price    pgtype.Numeric `json:"price"`
	UserID   string         `json:"user_id"`
}
