// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, item, quantity, price, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, item, quantity, price, user_id
`

type CreateOrderParams struct {
	ID       string         `json:"id"`
	Item     string         `json:"item"`
	Quantity int32          `json:"quantity"`
	Price    pgtype.Numeric `json:"price"`
	UserID   string         `json:"user_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Item,
		arg.Quantity,
		arg.Price,
		arg.UserID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Item,
		&i.Quantity,
		&i.Price,
		&i.UserID,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :execrows
DELETE FROM orders WHERE id = $1 AND user_id = $2
`

type DeleteOrderParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteOrder(ctx context.Context, arg DeleteOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrder, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, item, quantity, price, user_id FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Item,
		&i.Quantity,
		&i.Price,
		&i.UserID,
	)
	return i, err
}

const getOrders = `-- name: GetOrders :many
SELECT id, item, quantity, price, user_id FROM orders
WHERE user_id = $1
`

func (q *Queries) GetOrders(ctx context.Context, userID string) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Item,
			&i.Quantity,
			&i.Price,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET item = $2, quantity = $3, price = $4
WHERE id = $1 AND user_id = $5
RETURNING id, item, quantity, price, user_id
`

type UpdateOrderParams struct {
	ID       string         `json:"id"`
	Item     string         `json:"item"`
	Quantity int32          `json:"quantity"`
	Price    pgtype.Numeric `json:"price"`
	UserID   string         `json:"user_id"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.Item,
		arg.Quantity,
		arg.Price,
		arg.UserID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Item,
		&i.Quantity,
		&i.Price,
		&i.UserID,
	)
	return i, err
}
