// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	DeleteOrder(ctx context.Context, arg DeleteOrderParams) (int64, error)
	GetOrder(ctx context.Context, arg GetOrderParams) (Order, error)
	GetOrders(ctx context.Context, userID string) ([]Order, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
